_1.__ Установить, какие произведения матриц $AB$ и $BA$ определены, и найти размерности полученных матриц:

   а) $A$ — матрица $4\times 2$, $B$ — матрица $4\times 2$;
    
   б) $A$ — матрица $2\times 5$, $B$ — матрица $5\times 3$;
    
   в) $A$ — матрица $8\times 3$, $B$ — матрица $3\times 8$;
    
   г) $A$ — квадратная матрица $4\times 4$, $B$ — квадратная матрица $4\times 4$.
    
    

a) произведение не опреденено (необходимо, чтобы число столбцов матрицы А было равно числу строк матрицы B)

б)размерность АВ = 2х3 , размерность ВА = не определена

в)Размерность АВ = 8х8 , размерность ВА = 3х3


г)Матрицы квалратные, размерность 4х4

__2.__ Найти сумму и произведение матриц $A=\begin{pmatrix}
1 & -2\\ 
3 & 0
\end{pmatrix}$ и $B=\begin{pmatrix}
4 & -1\\ 
0 & 5
\end{pmatrix}.$

In [1]:
import numpy as np

In [2]:
a = np.array([[1, -2], [3, 0]])
b = np.array([[4, -1], [0, 5]])
print(f'Матрица:\n{a}')
print(f'Матрица:\n{b}')

Матрица:
[[ 1 -2]
 [ 3  0]]
Матрица:
[[ 4 -1]
 [ 0  5]]


In [3]:
print(f'Матрица С = A + B\n{a + b}')

Матрица С = A + B
[[ 5 -3]
 [ 3  5]]


In [5]:
print(f'Матрица AB\n{np.dot(a, b)}')
print(f'Матрица AB\n{a.dot(b)}')
print(f'Матрица AB\n{a @ b}')
print(f'Матрица BA\n{b.dot(a)}')

Матрица AB
[[  4 -11]
 [ 12  -3]]
Матрица AB
[[  4 -11]
 [ 12  -3]]
Матрица AB
[[  4 -11]
 [ 12  -3]]
Матрица BA
[[ 1 -8]
 [15  0]]


__3.__ Из закономерностей сложения и умножения матриц на число можно сделать вывод, что матрицы одного размера образуют линейное пространство. Вычислить линейную комбинацию $3A-2B+4C$ для матриц $A=\begin{pmatrix}
1 & 7\\ 
3 & -6
\end{pmatrix}$, $B=\begin{pmatrix}
0 & 5\\ 
2 & -1
\end{pmatrix}$, $C=\begin{pmatrix}
2 & -4\\ 
1 & 1
\end{pmatrix}.$

In [7]:
A = np.array([[1, 7], [3, -6]])
B = np.array([[0, 5], [2, -1]])
C = np.array([[2, -4], [1, 1]])

In [8]:
print(f'Матрица:\n{A}')
print(f'Матрица:\n{B}')
print(f'Матрица:\n{C}')

Матрица:
[[ 1  7]
 [ 3 -6]]
Матрица:
[[ 0  5]
 [ 2 -1]]
Матрица:
[[ 2 -4]
 [ 1  1]]


In [18]:
print(f'Матрица:\n{3*A}')
print(f'Матрица:\n{-2*B}')
print(f'Матрица:\n{4*C}')

Матрица:
[[  3  21]
 [  9 -18]]
Матрица:
[[  0 -10]
 [ -4   2]]
Матрица:
[[  8 -16]
 [  4   4]]


In [20]:
print(f'Матрица С = 3A-2B+4C\n{3*A + (-2*B) + 4*C}')

Матрица С = 3A-2B+4C
[[ 11  -5]
 [  9 -12]]


__4.__ Дана матрица $A=\begin{pmatrix}
4 & 1\\ 
5 & -2\\ 
2 & 3
\end{pmatrix}$.
Вычислить $AA^{T}$ и $A^{T}A$.

In [23]:
A = np.array([[4, 1], [5, -2], [2, 3]])
print(f'Матрица:\n{A}')
print(f'Транспонированная матрица:\n{A.T}')
At=A.T
print(f'Матрица AAt\n{np.dot(A, At)}')
print(f'Матрица AtA\n{np.dot(At, A)}')

Матрица:
[[ 4  1]
 [ 5 -2]
 [ 2  3]]
Транспонированная матрица:
[[ 4  5  2]
 [ 1 -2  3]]
Матрица AAt
[[17 18 11]
 [18 29  4]
 [11  4 13]]
Матрица AtA
[[45  0]
 [ 0 14]]


__5*.__ Написать на Python функцию для перемножения двух произвольных матриц, не используя NumPy.

In [59]:
A = [[1, 3, -3], [1, 4, 6]]
B = [[5, 26, 3], [7, 6, 1], [0,1,0]] 

c = [[None for __ in range(len(B[0]))] for __ in range(len(A))]   

for i in range(len(A)):
    for j in range(len(B[0])):       
        c[i][j] = sum(A[i][kk] * B[kk][j] for kk in range(n))
  
print(c)

print(f'Матрица AB\n{np.dot(A, B)}')

[[26, 41, 6], [33, 56, 7]]
Матрица AB
[[26 41  6]
 [33 56  7]]


__1.__ Вычислить определитель:

   a)

$$\begin{vmatrix}
sinx & -cosx\\ 
cosx & sinx
\end{vmatrix};$$

   б)
    
$$\begin{vmatrix}
4 & 2 & 3\\ 
0 & 5 & 1\\ 
0 & 0 & 9
\end{vmatrix};$$
    
   в)

$$\begin{vmatrix}
1 & 2 & 3\\ 
4 & 5 & 6\\ 
7 & 8 & 9
\end{vmatrix}.$$

a) sinxsinx+cosxcosx=sinx^2+cosx^2=1

In [45]:
b = np.array([[4, 2, 3], [0, 5, 1], [0, 0, 9]])
print(f'Матрица:\n{b}')
print(f'Определитель:\n{np.linalg.det(b):.0f}')

Матрица:
[[4 2 3]
 [0 5 1]
 [0 0 9]]
Определитель:
180


In [46]:
c = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(f'Матрица:\n{c}')
print(f'Определитель:\n{np.linalg.det(c):.0f}')

Матрица:
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Определитель:
0


__2.__ Определитель матрицы $A$ равен $4$. Найти:

   а) $det(A^{2})$;
    
   б) $det(A^{T})$;
    
   в) $det(2A)$.

__а)__ $det(A^{2})$ =$det(A)$x$det(A)$=16
__б)__ $detA^{T}=detA$ = 4
__в)__ $det(2A)$ =2^n$det(A)$

__3.__  Доказать, что матрица

$$\begin{pmatrix}
-2 & 7 & -3\\ 
4 & -14 & 6\\ 
-3 & 7 & 13
\end{pmatrix}$$
   
вырожденная.

In [47]:
a = np.array([[-2, 7, -3], [4, -14, 6], [-3, 7, 13]])
print(f'Матрица:\n{a}')
print(f'Определитель:\n{np.linalg.det(a):.0f}')

Матрица:
[[ -2   7  -3]
 [  4 -14   6]
 [ -3   7  13]]
Определитель:
0


Невырожденная матрица (иначе неособенная матрица) ― квадратная матрица, определитель которой отличен от нуля. В противном случае матрица называется вырожденной.

__4.__ Найти ранг матрицы:

   а) $\begin{pmatrix}
1 & 2 & 3\\ 
1 & 1 & 1\\ 
2 & 3 & 4
\end{pmatrix};$

   б) $\begin{pmatrix}
0 & 0 & 2 & 1\\ 
0 & 0 & 2 & 2\\ 
0 & 0 & 4 & 3\\ 
2 & 3 & 5 & 6
\end{pmatrix}.$

In [48]:
a = np.array([[1, 2, 3], [1, 1, 1], [2, 3, 4]])
r = np.linalg.matrix_rank(a)

print(f'Ранг матрицы A: {r}')

b = np.array([[0, 0, 2, 1], [0, 0, 2, 2], [0, 0, 4, 3], [2, 3, 5, 6]])
g = np.linalg.matrix_rank(b)

print(f'Ранг матрицы B: {g}')




Ранг матрицы A: 2
Ранг матрицы B: 3
